### ISSUE TITLE
Rendering Bug When Walking Around Edges

### ISSUE THREAD

**Issue by Floaterest** [nenikitov/ConsoleRayCaster#10]
In the newest version (0.5-beta), some part of the screen does not render when walking through blocks around the edge of the map. The problem doesn't happen for blocks in the middle of the map but the blocks on the edge.

# Expected Behavior
Correct rendering, something like this (image is photoshopped):
![good](https://user-images.githubusercontent.com/56704092/126368954-e2ceb71c-2f23-439d-a843-c5d949d349db.png)

# Current Behavior
20% of the screen are black, thus doesn't render:
![nogood](https://user-images.githubusercontent.com/56704092/126369028-dce4b67c-44c2-4b0d-a6f5-1673f79f981a.png)

# Steps to Reproduce
1. Execute `exec.bat`.
2. Walk straight to towards the edge of the map.
3. Stand inside the red block at the edge.
4. Part of the screen does not render depending on the camera angle.

# Detailed Description
(see `.gif` below)
![Animation](https://user-images.githubusercontent.com/56704092/126369651-23c3e900-1663-4b7f-9c81-38fbd84c17f9.gif)

**Comment by nenikitov** [comment]
Thanks for reporting this issue.
I know which part of rendering code causes this behavior and I will try to fix it by the next release. 

# Technical explanation
The renderer draws the scene by tracing the rays from left to right. When the ray does not hit anything, it skips the current column, filling it with black pixels. This has a side effect that, when looking out of bounds (where there are no walls to draw), it does not render anything, resulting into this black rectangle.
It should not be that hard to fix (hopefully).

**Comment by Floaterest** [comment]
Thank you for the quick response! I will be looking forward to the next release.

**Comment by nenikitov** [comment]
Please check out the new **v0.5.1-beta** release. It should fix the issue and enable the rendering of the sky outside the map.
It is available [here](https://github.com/nenikitov/ConsoleRayCaster/releases/tag/v0.5.1-beta).

**Comment by Floaterest** [comment]
But the wall still doesn't render (I'm using v0.5.1-beta).
![image](https://user-images.githubusercontent.com/56704092/126517365-53dfb91d-79c0-4d35-a468-01e6b2507340.png)

**Comment by nenikitov** [comment]
Thanks again for your feedback.
Unfortunately, this is expected behavior. Later, when I implement collisions, this effect should not be visible with regular walls. It should also help with seemingly opaque "secret" walls through which the play can pass through.
I hope to implement a collision system soon and hear back from you if this helped with this rendering issue.

# Technical explanation
The walls are rendered only from the front side; Only the sides of the wall which are perpendicular to the camera are drawn, and the other sides are see-through. This is a common practice in computer rendering (see [back-face culling](https://en.wikipedia.org/wiki/Back-face_culling) for more details).
That means that only the walls outside of the current tile are visible. This is why you see the walls on the left and the right (because they are from the adjacent tiles), and the sky in front (because there are no tiles in front, so the renderer draws the sky).

In practice, in this case, it can be used artistically. For example, to create "windows" through which the outside world will be visible. This effect can be seen by moving 3 tiles diagonally forward and right and traveling a bit further into the newly added hallway from the starting position. You will see the sky through the opening in the wall). I wanted to use this feature later to render the secret walls.

**Comment by nenikitov** [comment]
Sorry for the long wait. I finally implemented player collision and now the rendering issues are not visible.
Please try out new [**v0.6-beta**](https://github.com/nenikitov/ConsoleRayCaster/releases/tag/0.6-beta) release.

**Comment by Floaterest** [comment]
Thanks! I see this engine is getting better and better!
